//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokk.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisID { get; set; }
        public int Urun { get; set; }
        public int Musteri { get; set; }
        public byte Adet { get; set; }
        public decimal fiyat { get; set; }
    
        public virtual Musteri Musteri1 { get; set; }
        public virtual Urun Urun1 { get; set; }
    }
}
